version: "3"
services:
    showcase:
        build:
            context: .
        ports:
            - "${HTTP_PORT_GUNICORN:-8000}:8000"
        volumes:
            - .:/src
        links:
          - "ddagent:ddagent"
        environment:
          - DD_AGENT_HOST=ddagent
          - DD_AGENT_PORT=8126
          - DD_TRACE_AGENT_URL=http://ddagent:8126
          - DD_API_KEY=$DD_API_KEY
          - DD_SERVICE=albertovara_service_15
          - DD_TRACE_ENABLED=true
          - DD_APPSEC_ENABLED=true
          - _DD_TELEMETRY_METRICS_ENABLED=true
          - DD_REMOTE_CONFIGURATION_ENABLED=false
          - DD_ENV=staging
          - DD_TRACE_DEBUG=true
          - DD_VERSION=0.1
        depends_on:
          - "ddagent"
        user: "${UID}:${GID}"
    ddagent:
        image: datadog/agent:latest
        environment:
            - DD_HOSTNAME=github-actions-worker
            - DD_BIND_HOST=0.0.0.0
            - DD_REMOTE_CONFIGURATION_ENABLED=true
            - DD_API_KEY=$DD_API_KEY
            - DD_REMOTE_CONFIGURATION_REFRESH_INTERVAL=5s
            - DD_APM_RECEIVER_SOCKET=/tmp/ddagent/trace.sock
        ports:
            - "127.0.0.1:8126:8126"
        volumes:
          - ddagent:/tmp/ddagent:rw
volumes:
    ddagent:
